### ISSUE TITLE
Upgrade to node 20

### ISSUE THREAD

**Issue by gnuletik** [eLco/setup-terragrunt#1]
Hello !
Thanks for this action.

I get the following warning while running the CI:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: eLco/setup-terragrunt@v1.0.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Would it be possible to upgrade to node 20?

Thanks!

**Comment by eLco** [comment]
Hey, @gnuletik - bumped the node version and updated tag v1 to point to latest release v1.0.3

**Comment by gnuletik** [comment]
Awesome! Thanks for the fast fix!
